export { VoiceCoordinator } from './VoiceCoordinator';
export type { VoiceDeps } from './VoiceCoordinator';
export { AlertQueue } from './AlertQueue';
export { PHRASES, POLICIES, alertFromEvent, coachingTipAlert } from './phrases';
export type { PhraseId } from './phrases';
export { FallbackSpeaker } from './speakers/FallbackSpeaker';
export { BundledAudioSpeaker } from './speakers/BundledAudioSpeaker';
export { ElevenLabsSpeaker } from './speakers/ElevenLabsSpeaker';
export { DeviceTtsSpeaker } from './speakers/DeviceTtsSpeaker';
export type { AudioPlayer, TextToSpeech, AudioSource } from './speakers/ports';
export * from './types';
