import type { DriveEvent } from '../../core/events/types';
import type { Alert, AlertKind, SpokenStream } from './types';

export type AlertPolicy = {
  priority: number;
  ttlMs: number;
  cooldownMs: number;
};

export const POLICIES: Record<AlertKind, AlertPolicy> = {
  crash: { priority: 100, ttlMs: 10_000, cooldownMs: 5_000 },
  ran_stop: { priority: 80, ttlMs: 5_000, cooldownMs: 10_000 },
  // Location alerts carry a target (the sign, light or hotspot), and their cooldown applies per
  // target, so a second sign right behind the first is still announced. The ttl leaves room to
  // wait behind one ~3 s clip without being dropped.
  stop_sign_ahead: { priority: 70, ttlMs: 6_000, cooldownMs: 8_000 },
  // Hotspot warnings are spoken ~250 m out so they finish before the 150 m stop-sign alert,
  // which outranks them (README order: stop sign > highway > traffic light > swerve > tips).
  hotspot_ahead: { priority: 65, ttlMs: 8_000, cooldownMs: 3_000 },
  highway_entering: { priority: 58, ttlMs: 6_000, cooldownMs: 15_000 },
  highway_exiting: { priority: 58, ttlMs: 6_000, cooldownMs: 15_000 },
  traffic_light_ahead: { priority: 55, ttlMs: 6_000, cooldownMs: 5_000 },
  rolling_stop: { priority: 60, ttlMs: 5_000, cooldownMs: 10_000 },
  // Below stop signs and highway merges, above traffic lights; SpeedingCoach has its own cooldown.
  speeding: { priority: 57, ttlMs: 4_000, cooldownMs: 15_000 },
  erratic_driving: { priority: 50, ttlMs: 5_000, cooldownMs: 20_000 },
  hard_braking: { priority: 48, ttlMs: 5_000, cooldownMs: 20_000 },
  rapid_acceleration: { priority: 46, ttlMs: 5_000, cooldownMs: 20_000 },
  harsh_cornering: { priority: 46, ttlMs: 5_000, cooldownMs: 20_000 },
  stop_ok: { priority: 20, ttlMs: 4_000, cooldownMs: 15_000 },
  chat_reply: { priority: 30, ttlMs: 15_000, cooldownMs: 0 },
  // Gemini's on-the-spot remark after a notable moment. Below every predetermined clip, so it always
  // waits for them, and never interrupted once it starts (VoiceCoordinator). Dropped if it has waited
  // this long. LiveCoach throttles how often it asks.
  live_coach: { priority: 15, ttlMs: 15_000, cooldownMs: 0 },
  coaching_tip: { priority: 10, ttlMs: 30_000, cooldownMs: 60_000 },
};

/** Fixed phrases. Each id has bundled audio generated by `npm run phrases`. */
export const PHRASES = {
  crash_check: 'Possible crash detected. Are you okay?',
  crash_confirmed: 'Crash confirmed. Calling for help.',
  ran_stop: 'You ran that stop sign.',
  stop_sign_ahead: 'Stop sign ahead. Start slowing down.',
  rolling_stop: 'That was a rolling stop. Come to a full stop next time.',
  erratic_driving: 'Your driving looks unsteady. Take it easy and stay in your lane.',
  stop_ok: 'Nice stop.',
  traffic_light_ahead: 'Traffic light ahead.',
  speeding: "You're over the speed limit. Slow down.",
  highway_merge: 'Merging onto the highway. Speed up to match traffic.',
  highway_exit: 'Exit ahead. Slow down for the ramp.',
  hotspot_rolling: 'Heads up. Drivers often roll through the stop here.',
  hotspot_ran: 'Heads up. Drivers often run the stop here.',
  hotspot_erratic: 'Take extra care here. Other drivers often struggle in this area.',
  hard_braking: 'Brake more smoothly and leave extra space ahead.',
  rapid_acceleration: 'Ease onto the accelerator for a smoother start.',
  harsh_cornering: 'Slow down before the turn and steer smoothly.',
  reply_fallback: "Sorry, I can't answer that right now.",
} as const;

export type PhraseId = keyof typeof PHRASES;

/** Phrases with no generated ElevenLabs clip yet; run `npm run phrases` with a key, then remove them. */
export type PhraseWithoutAudio = never;
/** Phrases that have a bundled clip in assets/audio. */
export type BundledPhraseId = Exclude<PhraseId, PhraseWithoutAudio>;
const PHRASES_WITHOUT_AUDIO = new Set<PhraseId>([] satisfies PhraseWithoutAudio[]);

/** Fixed phrase for an event, or null when it should stay silent (e.g. a highway ramp taken at a good speed). */
function phraseFor(event: DriveEvent): PhraseId | null {
  switch (event.kind) {
    case 'crash':
      return event.confirmed ? 'crash_confirmed' : 'crash_check';
    case 'ran_stop':
      return 'ran_stop';
    case 'stop_sign_ahead':
      return 'stop_sign_ahead';
    case 'rolling_stop':
      return 'rolling_stop';
    case 'erratic_driving':
      return 'erratic_driving';
    case 'hard_braking':
    case 'rapid_acceleration':
    case 'harsh_cornering':
      return event.kind;
    case 'stop_ok':
      return 'stop_ok';
    case 'traffic_light_ahead':
      return 'traffic_light_ahead';
    case 'speeding':
      return 'speeding';
    case 'highway_entering':
      return event.advice === 'speed_up' ? 'highway_merge' : null;
    case 'highway_exiting':
      return event.advice === 'slow_down' ? 'highway_exit' : null;
    case 'hotspot_ahead':
      return event.topKind === 'ran_stop'
        ? 'hotspot_ran'
        : event.topKind === 'rolling_stop'
          ? 'hotspot_rolling'
          : 'hotspot_erratic';
  }
}

/** The sign, light or hotspot an alert is about, so cooldowns don't swallow a different one. */
function targetFor(event: DriveEvent): string | undefined {
  switch (event.kind) {
    case 'stop_sign_ahead':
    case 'traffic_light_ahead':
      return event.featureId !== undefined ? String(event.featureId) : undefined;
    case 'hotspot_ahead':
      return event.cell;
    default:
      return undefined;
  }
}

export function alertFromEvent(event: DriveEvent): Alert | null {
  const phraseId = phraseFor(event);
  if (!phraseId) return null;
  const policy = POLICIES[event.kind];
  // Every fixed phrase has a bundled ElevenLabs clip; device TTS is only the chain's last resort.
  const bundledPhraseId = PHRASES_WITHOUT_AUDIO.has(phraseId) ? undefined : phraseId;
  const target = targetFor(event);
  return {
    id: event.eventId,
    kind: event.kind,
    priority: policy.priority,
    utterance: { text: PHRASES[phraseId], phraseId: bundledPhraseId },
    createdAt: event.t,
    ttlMs: policy.ttlMs,
    ...(target !== undefined ? { target } : {}),
  };
}

export function coachingTipAlert(id: string, text: string, now: number): Alert {
  const policy = POLICIES.coaching_tip;
  return {
    id,
    kind: 'coaching_tip',
    priority: policy.priority,
    utterance: { text },
    createdAt: now,
    ttlMs: policy.ttlMs,
  };
}

/** Spoken answer to a driver's question. Outranks tips, never outranks a safety alert. */
export function chatReplyAlert(id: string, text: string, now: number): Alert {
  const policy = POLICIES.chat_reply;
  return {
    id,
    kind: 'chat_reply',
    priority: policy.priority,
    utterance: text === REPLY_FALLBACK_TEXT ? { text, phraseId: 'reply_fallback' } : { text },
    createdAt: now,
    ttlMs: policy.ttlMs,
  };
}

/** A live coaching remark from Gemini, spoken with the phone's built-in voice for speed. */
export function liveCoachAlert(id: string, text: string, now: number): Alert {
  const policy = POLICIES.live_coach;
  return {
    id,
    kind: 'live_coach',
    priority: policy.priority,
    utterance: { text, deviceVoice: true },
    createdAt: now,
    ttlMs: policy.ttlMs,
  };
}

export const REPLY_FALLBACK_TEXT = PHRASES.reply_fallback;

/** A chat reply that is still streaming in. Outranks tips, never a safety alert. */
export function chatReplyStreamAlert(id: string, stream: SpokenStream, now: number): Alert {
  return {
    ...chatReplyAlert(id, REPLY_FALLBACK_TEXT, now),
    utterance: { text: REPLY_FALLBACK_TEXT, phraseId: 'reply_fallback', stream },
  };
}
