import type { DriveEvent } from '../../core/events/types';
import type { Alert, AlertKind } from './types';

export type AlertPolicy = {
  priority: number;
  ttlMs: number;
  cooldownMs: number;
};

export const POLICIES: Record<AlertKind, AlertPolicy> = {
  crash: { priority: 100, ttlMs: 10_000, cooldownMs: 5_000 },
  ran_stop: { priority: 80, ttlMs: 5_000, cooldownMs: 10_000 },
  stop_sign_ahead: { priority: 70, ttlMs: 3_000, cooldownMs: 8_000 },
  rolling_stop: { priority: 60, ttlMs: 5_000, cooldownMs: 10_000 },
  erratic_driving: { priority: 50, ttlMs: 5_000, cooldownMs: 20_000 },
  stop_ok: { priority: 20, ttlMs: 4_000, cooldownMs: 15_000 },
  coaching_tip: { priority: 10, ttlMs: 30_000, cooldownMs: 60_000 },
};

/** Fixed phrases. Each id has bundled audio generated by `npm run phrases`. */
export const PHRASES = {
  crash_check: 'Crash detected. Are you okay?',
  crash_confirmed: 'Crash confirmed. Calling for help.',
  ran_stop: 'You ran that stop sign.',
  stop_sign_ahead: 'Stop sign ahead. Start slowing down.',
  rolling_stop: 'That was a rolling stop. Come to a full stop next time.',
  erratic_driving: 'Your driving looks unsteady. Take it easy and stay in your lane.',
  stop_ok: 'Nice stop.',
} as const;

export type PhraseId = keyof typeof PHRASES;

function phraseFor(event: DriveEvent): PhraseId {
  switch (event.kind) {
    case 'crash':
      return event.confirmed ? 'crash_confirmed' : 'crash_check';
    case 'ran_stop':
      return 'ran_stop';
    case 'stop_sign_ahead':
      return 'stop_sign_ahead';
    case 'rolling_stop':
      return 'rolling_stop';
    case 'erratic_driving':
      return 'erratic_driving';
    case 'stop_ok':
      return 'stop_ok';
  }
}

export function alertFromEvent(event: DriveEvent): Alert {
  const phraseId = phraseFor(event);
  const policy = POLICIES[event.kind];
  return {
    id: event.eventId,
    kind: event.kind,
    priority: policy.priority,
    utterance: { text: PHRASES[phraseId], phraseId },
    createdAt: event.t,
    ttlMs: policy.ttlMs,
  };
}

export function coachingTipAlert(id: string, text: string, now: number): Alert {
  const policy = POLICIES.coaching_tip;
  return {
    id,
    kind: 'coaching_tip',
    priority: policy.priority,
    utterance: { text },
    createdAt: now,
    ttlMs: policy.ttlMs,
  };
}
