import type { DriveEvent } from '../../core/events/types';
import type { Alert, AlertKind, SpokenStream } from './types';

export type AlertPolicy = {
  priority: number;
  ttlMs: number;
  cooldownMs: number;
};

export const POLICIES: Record<AlertKind, AlertPolicy> = {
  crash: { priority: 100, ttlMs: 10_000, cooldownMs: 5_000 },
  ran_stop: { priority: 80, ttlMs: 5_000, cooldownMs: 10_000 },
  stop_sign_ahead: { priority: 70, ttlMs: 3_000, cooldownMs: 8_000 },
  // Hotspot warnings are spoken ~250 m out so they finish before the 150 m stop-sign alert,
  // which outranks them (README order: stop sign > highway > traffic light > swerve > tips).
  hotspot_ahead: { priority: 65, ttlMs: 6_000, cooldownMs: 3_000 },
  highway_entering: { priority: 58, ttlMs: 6_000, cooldownMs: 15_000 },
  highway_exiting: { priority: 58, ttlMs: 6_000, cooldownMs: 15_000 },
  traffic_light_ahead: { priority: 55, ttlMs: 4_000, cooldownMs: 5_000 },
  rolling_stop: { priority: 60, ttlMs: 5_000, cooldownMs: 10_000 },
  // Below stop signs and highway merges, above traffic lights; SpeedingCoach has its own cooldown.
  speeding: { priority: 57, ttlMs: 4_000, cooldownMs: 15_000 },
  erratic_driving: { priority: 50, ttlMs: 5_000, cooldownMs: 20_000 },
  stop_ok: { priority: 20, ttlMs: 4_000, cooldownMs: 15_000 },
  chat_reply: { priority: 30, ttlMs: 15_000, cooldownMs: 0 },
  coaching_tip: { priority: 10, ttlMs: 30_000, cooldownMs: 60_000 },
};

/** Fixed phrases. Each id has bundled audio generated by `npm run phrases`. */
export const PHRASES = {
  crash_check: 'Possible crash detected. Are you okay?',
  crash_confirmed: 'Crash confirmed. Calling for help.',
  ran_stop: 'You ran that stop sign.',
  stop_sign_ahead: 'Stop sign ahead. Start slowing down.',
  rolling_stop: 'That was a rolling stop. Come to a full stop next time.',
  erratic_driving: 'Your driving looks unsteady. Take it easy and stay in your lane.',
  stop_ok: 'Nice stop.',
  traffic_light_ahead: 'Traffic light ahead.',
  speeding: "You're over the speed limit. Slow down.",
  highway_merge: 'Merging onto the highway. Speed up to match traffic.',
  highway_exit: 'Exit ahead. Slow down for the ramp.',
  hotspot_rolling: 'Heads up. Drivers often roll through the stop here.',
  hotspot_ran: 'Heads up. Drivers often run the stop here.',
  hotspot_erratic: 'Take extra care here. Other drivers often struggle in this area.',
} as const;

export type PhraseId = keyof typeof PHRASES;

/** Phrases with no generated ElevenLabs clip yet; run `npm run phrases` with a key, then remove them. */
export type PhraseWithoutAudio = 'speeding';
/** Phrases that have a bundled clip in assets/audio. */
export type BundledPhraseId = Exclude<PhraseId, PhraseWithoutAudio>;
const PHRASES_WITHOUT_AUDIO = new Set<PhraseId>(['speeding'] satisfies PhraseWithoutAudio[]);

/** Fixed phrase for an event, or null when it should stay silent (e.g. a highway ramp taken at a good speed). */
function phraseFor(event: DriveEvent): PhraseId | null {
  switch (event.kind) {
    case 'crash':
      return event.confirmed ? 'crash_confirmed' : 'crash_check';
    case 'ran_stop':
      return 'ran_stop';
    case 'stop_sign_ahead':
      return 'stop_sign_ahead';
    case 'rolling_stop':
      return 'rolling_stop';
    case 'erratic_driving':
      return 'erratic_driving';
    case 'stop_ok':
      return 'stop_ok';
    case 'traffic_light_ahead':
      return 'traffic_light_ahead';
    case 'speeding':
      return 'speeding';
    case 'highway_entering':
      return event.advice === 'speed_up' ? 'highway_merge' : null;
    case 'highway_exiting':
      return event.advice === 'slow_down' ? 'highway_exit' : null;
    case 'hotspot_ahead':
      return event.topKind === 'ran_stop'
        ? 'hotspot_ran'
        : event.topKind === 'rolling_stop'
          ? 'hotspot_rolling'
          : 'hotspot_erratic';
  }
}

export function alertFromEvent(event: DriveEvent): Alert | null {
  const phraseId = phraseFor(event);
  if (!phraseId) return null;
  const policy = POLICIES[event.kind];
  // No bundled clip for these yet, so they use device TTS (see PHRASES_WITHOUT_AUDIO).
  const bundledPhraseId =
    (event.kind === 'crash' && !event.confirmed) || PHRASES_WITHOUT_AUDIO.has(phraseId) ? undefined : phraseId;
  return {
    id: event.eventId,
    kind: event.kind,
    priority: policy.priority,
    // The existing crash_check asset says "Crash detected". An unconfirmed heuristic candidate uses
    // device TTS instead, so it is accurately presented as a possible crash.
    utterance: { text: PHRASES[phraseId], phraseId: bundledPhraseId },
    createdAt: event.t,
    ttlMs: policy.ttlMs,
  };
}

export function coachingTipAlert(id: string, text: string, now: number): Alert {
  const policy = POLICIES.coaching_tip;
  return {
    id,
    kind: 'coaching_tip',
    priority: policy.priority,
    utterance: { text },
    createdAt: now,
    ttlMs: policy.ttlMs,
  };
}

/** Spoken answer to a driver's question. Outranks tips, never outranks a safety alert. */
export function chatReplyAlert(id: string, text: string, now: number): Alert {
  const policy = POLICIES.chat_reply;
  return {
    id,
    kind: 'chat_reply',
    priority: policy.priority,
    utterance: { text },
    createdAt: now,
    ttlMs: policy.ttlMs,
  };
}

export const REPLY_FALLBACK_TEXT = "Sorry, I can't answer that right now.";

/** A chat reply that is still streaming in. Outranks tips, never a safety alert. */
export function chatReplyStreamAlert(id: string, stream: SpokenStream, now: number): Alert {
  return { ...chatReplyAlert(id, REPLY_FALLBACK_TEXT, now), utterance: { text: REPLY_FALLBACK_TEXT, stream } };
}
